"use client";

import { Fragment, useState } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Check,
  CircleDot,
  Hand,
  ImagePlus,
  Maximize2,
  MousePointer2,
  Play,
  Plus,
  Sparkles,
} from "lucide-react";
import { getActiveWorkflow, useWorkflowStore, type WorkflowNode } from "@/lib/store";

type Tool = "select" | "hand";

function NodeGlyph({ type }: { type: WorkflowNode["type"] }) {
  if (type === "prompt") return <Sparkles className="size-4" strokeWidth={1.8} />;
  if (type === "reference") return <ImagePlus className="size-4" strokeWidth={1.8} />;
  return <CircleDot className="size-4" strokeWidth={1.8} />;
}

const nodeAccent = (type: WorkflowNode["type"]) => {
  if (type === "prompt") return { text: "text-emerald-200", bg: "bg-emerald-300/10", border: "border-emerald-200/20" };
  if (type === "reference") return { text: "text-sky-200", bg: "bg-sky-300/10", border: "border-sky-200/20" };
  return { text: "text-orange-200", bg: "bg-orange-300/10", border: "border-orange-200/20" };
};

function NodeCard({ node, index, focused, onFocus, onChange }: { node: WorkflowNode; index: number; focused: boolean; onFocus: () => void; onChange: (value: string, imageUrl?: string) => void }) {
  const accent = nodeAccent(node.type);
  const isActive = node.type === "image" && Boolean(node.imageUrl);

  return <article className={`composer-node group w-[min(330px,calc(100vw-3rem))] shrink-0 rounded-2xl border bg-[#11151d]/95 shadow-2xl shadow-black/25 backdrop-blur-xl transition duration-200 hover:-translate-y-0.5 hover:border-white/20 ${accent.border} ${focused ? "ring-2 ring-teal-200/25" : ""} ${isActive ? "ring-1 ring-orange-200/15" : ""}`} onClick={onFocus}>
    <div className="flex items-center justify-between border-b border-white/8 px-4 py-3"><div className="flex min-w-0 items-center gap-3"><div className={`grid size-9 shrink-0 place-items-center rounded-xl ${accent.bg} ${accent.text}`}><NodeGlyph type={node.type} /></div><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-white/30">Step {String(index + 1).padStart(2, "0")}</p><h2 className="truncate text-sm font-medium text-white/85">{node.title}</h2></div></div><span className="text-[10px] uppercase tracking-[0.14em] text-white/25">{node.type === "image" ? "Output" : "Input"}</span></div>
    <div className="p-4">
      {node.type === "prompt" && <label className="block"><span className="mb-2 block text-xs text-white/40">Describe the transformation</span><textarea value={node.value} onChange={(event) => onChange(event.target.value)} placeholder="A cinematic subject, a considered palette…" className="min-h-32 w-full resize-y rounded-xl border border-white/10 bg-[#0a0d13] px-3 py-3 text-sm leading-6 text-white outline-none transition placeholder:text-white/20 focus:border-emerald-200/50 focus:bg-[#0c1017]" /></label>}
      {node.type === "reference" && <label className="block"><span className="mb-2 block text-xs text-white/40">Reference image URL</span><input type="url" value={node.imageUrl || ""} onChange={(event) => onChange(event.target.value, event.target.value)} placeholder="/api/media/references/…" className="h-10 w-full rounded-xl border border-white/10 bg-[#0a0d13] px-3 text-xs text-white outline-none transition placeholder:text-white/20 focus:border-sky-200/50 focus:bg-[#0c1017]" />{node.imageUrl ? <img src={node.imageUrl} alt="Workflow reference" className="mt-3 aspect-[4/3] w-full rounded-xl border border-white/10 object-cover" /> : <div className="mt-3 grid aspect-[4/3] place-items-center rounded-xl border border-dashed border-white/10 bg-white/[0.015] text-xs text-white/25"><div className="text-center"><ImagePlus className="mx-auto mb-2 size-5" /><span>Paste a local image URL</span></div></div>}</label>}
      {node.type === "image" && (node.imageUrl ? <div><div className="relative overflow-hidden rounded-xl border border-orange-200/15 bg-black"><img src={node.imageUrl} alt="Generated workflow output" className="aspect-square w-full object-cover" /><div className="absolute bottom-2 left-2 flex items-center gap-1.5 rounded-md bg-black/70 px-2 py-1 text-[10px] text-orange-100 backdrop-blur"><Check className="size-3" /> Generated by Codex</div></div><p className="mt-3 text-xs leading-5 text-white/35">Ready to continue into another image operation.</p></div> : <div className="grid aspect-square place-items-center rounded-xl border border-dashed border-orange-200/15 bg-orange-200/[0.02] text-center"><div><div className="mx-auto mb-3 grid size-11 place-items-center rounded-full border border-orange-200/20 bg-orange-200/8 text-orange-200/70"><Sparkles className="size-5" /></div><p className="text-xs text-white/35">Your Codex output will appear here</p></div></div>)}
    </div>
  </article>;
}

export default function WorkflowCanvas() {
  const workflow = useWorkflowStore(getActiveWorkflow);
  const addNode = useWorkflowStore((state) => state.addNode);
  const updateNode = useWorkflowStore((state) => state.updateNode);
  const [running, setRunning] = useState(false);
  const [tool, setTool] = useState<Tool>("select");
  const [focusedNode, setFocusedNode] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!workflow) return <div className="grid min-h-screen flex-1 place-items-center bg-[#0a0c12] text-sm text-white/45">Workflow not found.</div>;
  const currentWorkflow = workflow;

  async function run() {
    const prompt = currentWorkflow.nodes.find((node) => node.type === "prompt")?.value || "";
    const refs = currentWorkflow.nodes.filter((node) => node.type === "reference" && node.imageUrl).map((node) => node.imageUrl!);
    if (!prompt.trim()) { setError("Add a prompt before running the workflow."); return; }
    setError(null); setRunning(true);
    try {
      const response = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, imageUrls: refs, aspectRatio: "1:1", quality: "auto" }) });
      const data = await response.json() as { taskId?: string; error?: string };
      if (!response.ok || !data.taskId) throw new Error(data.error || "Generation failed");
      let result: { status: string; imageUrl?: string; error?: string } = { status: "pending" };
      for (let attempt = 0; attempt < 120 && result.status === "pending"; attempt++) { await new Promise((resolve) => setTimeout(resolve, 1000)); result = await fetch(`/api/job-status?taskId=${data.taskId}`).then((res) => res.json()); }
      if (!result.imageUrl) throw new Error(result.error || "Codex did not return an image.");
      const output = currentWorkflow.nodes.find((node) => node.type === "image");
      if (output) updateNode(output.id, result.imageUrl, result.imageUrl);
    } catch (runError) { setError(runError instanceof Error ? runError.message : "Generation failed."); } finally { setRunning(false); }
  }

  return <main className="relative flex min-h-0 flex-1 flex-col overflow-hidden bg-[#0a0c12] text-white">
    <header className="z-20 flex min-h-16 shrink-0 items-center gap-3 border-b border-white/8 bg-[#0a0c12]/90 px-4 backdrop-blur-xl sm:px-6"><Link href="/workflow" className="grid size-9 shrink-0 place-items-center rounded-lg border border-white/10 text-white/45 transition hover:border-white/25 hover:text-white" aria-label="Back to workflows"><ArrowLeft className="size-4" /></Link><div className="min-w-0 flex-1"><p className="hidden text-[10px] font-semibold uppercase tracking-[0.2em] text-teal-200/45 sm:block">Workflow composer</p><h1 className="truncate text-sm font-medium text-white/90">{currentWorkflow.name}</h1></div><div className="hidden items-center gap-2 text-[11px] text-white/30 sm:flex"><span className="size-1.5 rounded-full bg-emerald-300" />{currentWorkflow.nodes.length} steps <span className="mx-1 text-white/15">·</span> Draft saved</div><button type="button" onClick={() => void run()} disabled={running} className="inline-flex h-9 items-center gap-2 rounded-lg bg-teal-300 px-3.5 text-xs font-semibold text-[#062522] shadow-lg shadow-teal-950/20 transition hover:bg-teal-200 disabled:cursor-wait disabled:opacity-50"><Play className="size-3.5" />{running ? "Running…" : "Run Codex"}</button></header>
    <div className={`relative min-h-0 flex-1 overflow-hidden ${tool === "hand" ? "cursor-grab active:cursor-grabbing" : ""}`}><div className="composer-grid absolute inset-0" /><div className="composer-glow absolute left-1/2 top-1/2 size-[min(70vw,700px)] -translate-x-1/2 -translate-y-1/2 rounded-full" /><div className="absolute left-5 top-5 z-10 hidden items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-white/25 md:flex"><span className="size-1.5 rounded-full bg-teal-200/70" /> Codex pipeline <span className="text-white/10">/</span> {workflow.name}</div>
      <div className="relative h-full overflow-auto px-5 pb-28 pt-20 sm:px-12 sm:pb-28 sm:pt-24"><div className={`mx-auto flex min-h-[480px] w-max max-w-none items-center gap-5 ${currentWorkflow.nodes.length > 1 ? "flex-col sm:flex-row" : ""}`}>{currentWorkflow.nodes.map((node, index) => <Fragment key={node.id}><NodeCard node={node} index={index} focused={focusedNode === node.id} onFocus={() => setFocusedNode(node.id)} onChange={(value, imageUrl) => updateNode(node.id, value, imageUrl)} />{index < currentWorkflow.nodes.length - 1 && <div className="composer-connector relative h-10 w-px shrink-0 bg-white/15 sm:h-px sm:w-16"><span className="absolute left-1/2 top-1/2 size-2 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/35 bg-[#0a0c12]" /></div>}</Fragment>)}{currentWorkflow.nodes.length === 0 && <div className="rounded-2xl border border-dashed border-white/15 bg-white/[0.02] px-8 py-12 text-center"><Sparkles className="mx-auto mb-4 size-7 text-teal-200/70" /><p className="text-sm text-white/60">Start your image pipeline</p><p className="mt-2 text-xs text-white/30">Add a prompt or reference step below.</p></div>}</div></div>
      {error && <div role="alert" className="absolute bottom-20 left-1/2 z-20 max-w-[calc(100%-2rem)] -translate-x-1/2 rounded-lg border border-red-200/20 bg-[#241518]/95 px-4 py-3 text-xs text-red-100 shadow-2xl">{error}</div>}
      <div className="absolute bottom-5 left-5 z-20 flex items-center gap-1 rounded-xl border border-white/10 bg-[#11151d]/90 p-1.5 shadow-2xl shadow-black/25 backdrop-blur-xl" aria-label="Canvas tools"><button type="button" onClick={() => setTool("select")} className={`grid size-9 place-items-center rounded-lg transition ${tool === "select" ? "bg-white/10 text-white" : "text-white/35 hover:text-white"}`} aria-label="Select tool" aria-pressed={tool === "select"}><MousePointer2 className="size-4" /></button><button type="button" onClick={() => setTool("hand")} className={`grid size-9 place-items-center rounded-lg transition ${tool === "hand" ? "bg-white/10 text-white" : "text-white/35 hover:text-white"}`} aria-label="Pan canvas" aria-pressed={tool === "hand"}><Hand className="size-4" /></button><span className="mx-1 h-5 w-px bg-white/10" /><button type="button" onClick={() => addNode("prompt")} className="grid size-9 place-items-center rounded-lg text-white/35 transition hover:bg-white/8 hover:text-white" aria-label="Add prompt step"><Plus className="size-4" /></button><button type="button" onClick={() => addNode("reference")} className="grid size-9 place-items-center rounded-lg text-white/35 transition hover:bg-white/8 hover:text-white" aria-label="Add reference step"><ImagePlus className="size-4" /></button></div>
      <div className="absolute bottom-5 right-5 z-20 hidden items-center gap-1 rounded-xl border border-white/10 bg-[#11151d]/90 p-1.5 shadow-2xl shadow-black/25 backdrop-blur-xl sm:flex"><button type="button" onClick={() => setFocusedNode(null)} className={`grid size-9 place-items-center rounded-lg transition ${focusedNode ? "text-teal-200" : "text-white/30 hover:text-white"}`} aria-label="Clear node focus"><Maximize2 className="size-4" /></button></div>
      <div className="absolute right-5 top-5 z-10 hidden rounded-lg border border-white/8 bg-[#11151d]/75 px-3 py-2 text-[11px] text-white/35 backdrop-blur-xl xl:block"><span className="text-white/55">Tip</span><span className="mx-2 text-white/15">·</span>Chain reference images into a Codex edit</div>
    </div>
  </main>;
}
